### ISSUE TITLE
Error encountered when launching Course in the CTS

### ISSUE THREAD

**Issue by L1ncx** [adlnet/CATAPULT#40]
I'm encountering this error when trying to launch a course I uploaded (from course_package) in the AU > Launch

![image](https://user-images.githubusercontent.com/12523381/170384945-f084ea59-5fa4-4e23-95b3-7c0cdcc6efe8.png)
![image](https://user-images.githubusercontent.com/12523381/170384992-eac50f41-86d8-4702-9e5e-768fc180adb5.png)

This is my cts/.env configuration

![image](https://user-images.githubusercontent.com/12523381/170384666-945f7ef9-e0a2-434f-a16c-ac9ac56bcdc5.png)

I've read in the other issues that it may need to install an actual LRS, is this also the case here?

**Comment by artstood** [comment]
As far as I remmember I`ve faced the same problem, and yes the link to actual LRS solved this issue. You can install it locally or use the cloud. I used LRS.io in cloud but there also could be problems with that

**Comment by catmeme** [comment]
Easiest local LRS to add locally, then link your other services by adding `- lrs` under their `depends_on`

```
  lrs:
    environment:
      - LRSQL_API_KEY_DEFAULT=basic_secret
      - LRSQL_API_SECRET_DEFAULT=basic_secret
      - LRSQL_ADMIN_USER_DEFAULT=basic_secret
      - LRSQL_ADMIN_PASS_DEFAULT=basic_secret
      - LRSQL_DB_NAME=lrsql.sqlite.db
    image: yetanalytics/lrsql
    ports:
      - "8080:8080"
    networks:
      - public

```
